### ISSUE TITLE
Some more detection possibilities

### ISSUE THREAD

**Issue by pfefferle** [michielbdejong/useraddress#2]
- Salmon as (C)omment via XRD/Webfinger
- XMPP or E-Mail as (M)ESSAGE via XRD/Webfinger (if identifier is Webfinger, than mailing to this address would mostly be possible)

**Comment by michielbdejong** [comment]
yes, thanks! i agree on salmon, not sure about implicit xmpp and email in case of webfinger. Think of StatusNet, Friendica and Diaspora, none of them have either afaik. if a host does support it then the thing to do would be to announce it explicitly in the xrd record with for instance <link rel="me" href="mailto:user@host"/> <link rel="me" href="xmpp:user@host"/> or a similar syntax?

**Comment by pfefferle** [comment]
You are right with webfinger as E-Mail addresses...

What about "email" and "impp" in hCards via "rel-me" or "http://webfinger.net/rel/profile-page" links?

Im proposing informations via XRD i would prefer the property tag: &lt;property type="email"&gt;max@example.com&lt;/property&gt; but this is for future plans :)

**Comment by michielbdejong** [comment]
can you give an example of a person who announces their email address
in the ways you mention? if it's used somewhere, i'll implement it so
that that person's email address and JID are discovered correctly by
the parser(s).

On Mon, Jul 30, 2012 at 1:44 PM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by pfefferle** [comment]
That's the problem, the properties are not really used today, but something like that was planned by concepting webfinger. From the google-code page:

<blockquote>whether the email address is also a JID, or explicitly declare that it's NOT an email, and ONLY a JID, or any combination to disambiguate all the addresses that look like something@somewhere.com</blockquote>


(http://code.google.com/p/webfinger/)

But not yet specified.

**Comment by michielbdejong** [comment]
if your WordPress plugin allows for exposing an email address inside
some xrd link property or similar, then i will add whatever syntax you
use for that to the parser.

On Mon, Jul 30, 2012 at 1:53 PM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by pfefferle** [comment]
should we start a wiki page on the unhosted wiki page to define some properties?

something like webfinger-simple-profile-fields based on the v/hCard standard like

&lt;Property type="http://some.uri/name" &gt;Max Mustermann&lt;Property&gt;
&lt;Property type="http://some.uri/email" &gt;max@test.de&lt;Property&gt;
&lt;Property type="http://some.uri/impp" &gt;max@test.de&lt;Property&gt;

and/or

&lt;Property type="http://some.uri/isemail" &gt;true&lt;Property&gt;
&lt;Property type="http://some.uri/isjid" &gt;true&lt;Property&gt;

to identify if the webfinger-identifier can also be used as JID or E-Mail.

If we find a good solution I will also add them to the plugin as a first use-case.

**Comment by pfefferle** [comment]
As rel values are like the following http://webfinger.net/rel/profile-page we could use http://webfinger.net/type/is-email or http://webfinger.net/type/is-jid but I don't know where to propose these urls...

**Comment by michielbdejong** [comment]
propose it on the public-fedsocweb@w3.org

On Mon, Jul 30, 2012 at 2:12 PM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by pfefferle** [comment]
thanks for posting it. will participate on the discussion.

I had a closer look at the latest IETF spec and found something under: Example Message Exchange Using the "acct" Link Relation (http://tools.ietf.org/html/draft-ietf-appsawg-webfinger-00)

```
 {
   "subject" : "acct:bob@example.net",
   "links" :
   [
     {
       "rel" : "acct",
       "href" : "acct:bob@example.com"
     },
     {
       "rel" : "acct",
       "href" : "acct:bob@example.org"
     },

     {
       "rel" : "acct",
       "href" : "mailto:bob@example.net"
     }
   ]
 }
```

will add that to the next version of my plugin:

{
"rel" : "acct",
"href" : "mailto:bob@example.net"
}

and

{
"rel" : "acct",
"href" : "xmpp:bob@example.net"
}

**Comment by michielbdejong** [comment]
cool!

On Mon, Jul 30, 2012 at 2:30 PM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by pfefferle** [comment]
after some more thoughts, i think it makes more sense to add all other identifiers as &lt;Aliases /&gt; because the represent the same user on the same wordpress blog and rel-acct is more like a link to other webfinger profiles on different servers. so i will add the mail address and the jid as aliases.

**Comment by michielbdejong** [comment]
cool! i'll add it to the parser, that's easy enough. as i said, it
might make sense to propose this on the public-fedsocweb@w3.org
mailing list.

On Tue, Jul 31, 2012 at 9:44 AM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by pfefferle** [comment]
Done! The latest version in the WordPress plugin-directory now displays all possible aliases for a user. you can see a demo here: http://notizblog.org/?webfinger-uri=acct:pfefferle@notizblog.org&format=json

don't you think the webfinger group is a better place to talk about that problem?

**Comment by michielbdejong** [comment]
cool!

ah yes, also a good one

On Tue, Jul 31, 2012 at 2:49 PM, Matthias Pfefferle
reply@reply.github.com
wrote:

**Comment by melvincarvalho** [comment]
Been playing around with this today ... looks pretty good ... I think it's the right approach to do identity on the web

One small point:

http://melvincarvalho.com/ is a document describing me ... I need to be able to look up the person which is http://melvincarvalho.com/#me

Same applies to Timbl's web page but with #i

You can still work by assuming a person is a web page, to an extent, and this can get you going ... but somewhere down the line something is going to break.  Better to model things accurately at the start, rather than have to rework/rewrite everything later.
